/**
 * Assembles the web shell's generated assets into docs/javascripts/tutor/.
 *
 * Three outputs, all gitignored, all regenerated by `npm run build:web`:
 *
 *   tutor-core.js        the harness core, bundled as a classic IIFE exposing
 *                        `window.TutorCore`. The shell scripts are hand-written
 *                        ES5-ish IIFEs (README §1 constraint 2: no bundler for
 *                        the site itself), so the core has to arrive as one
 *                        global rather than as modules they import.
 *   vendor/marked.js     pinned, copied from node_modules — NOT a CDN, because
 *   vendor/purify.js     the API key lives in localStorage on this origin and
 *                        every extra third-party script is another read of it
 *                        (README §6).
 *
 * The point of copying rather than vendoring by hand is that the version is in
 * package.json where `npm audit` can see it, and a bump is one install away.
 */

import { cpSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { build } from 'esbuild';

const here = dirname(fileURLToPath(import.meta.url));
const tutorRoot = resolve(here, '..');
const repoRoot = resolve(tutorRoot, '..');
const outDir = resolve(repoRoot, 'docs/javascripts/tutor');
const vendorDir = resolve(outDir, 'vendor');

const pkg = JSON.parse(readFileSync(resolve(tutorRoot, 'package.json'), 'utf8'));

mkdirSync(vendorDir, { recursive: true });

// ---------------------------------------------------------------------------
// 1. The core bundle
// ---------------------------------------------------------------------------

const result = await build({
  // The web shell entry, which re-exports the core surface the UI needs. Bundling
  // the shell rather than the core means the platform-import assertion below also
  // covers the adapters, and the UI gets one global instead of two.
  entryPoints: [resolve(tutorRoot, 'src/shells/web/index.ts')],
  bundle: true,
  format: 'iife',
  globalName: 'TutorCore',
  // Material supports evergreen browsers; es2020 keeps optional chaining and
  // nullish coalescing native rather than downlevelled into noise.
  target: ['es2020'],
  outfile: resolve(outDir, 'tutor-core.js'),
  sourcemap: true,
  // Not minified on purpose: this file is read by anyone auditing what the page
  // does with their API key, and the site has no bundle-size budget.
  minify: false,
  banner: {
    js:
      `/* @lecture-annotation/tutor core v${pkg.version} — GENERATED by ` +
      'tutor/scripts/build-web.mjs, do not edit. Source: tutor/src/core/ */',
  },
  metafile: true,
  logLevel: 'warning',
});

// A `node:*` import would have been resolved by esbuild into a browser shim or a
// hard error depending on the module, and either way the layering rule in
// README §2 has been broken. Assert it here so the failure names the cause.
const inputs = Object.keys(result.metafile.outputs[
  Object.keys(result.metafile.outputs).find((k) => k.endsWith('tutor-core.js'))
].inputs);
const platformImports = inputs.filter((p) => p.startsWith('node:') || p.includes('node_modules'));
if (platformImports.length > 0) {
  throw new Error(
    `core bundle pulled in non-browser modules: ${platformImports.join(', ')}\n` +
      'src/core/ must import neither node:* nor any dependency (ports.ts is the seam).',
  );
}

// ---------------------------------------------------------------------------
// 2. Vendored markdown + sanitiser
// ---------------------------------------------------------------------------

const vendored = [
  ['marked/lib/marked.umd.js', 'marked.js', 'marked'],
  ['dompurify/dist/purify.js', 'purify.js', 'dompurify'],
];

for (const [from, to, name] of vendored) {
  const version = pkg.devDependencies[name];
  const src = resolve(tutorRoot, 'node_modules', from);
  const dest = resolve(vendorDir, to);
  cpSync(src, dest);
  // Prepend provenance so the copy in docs/ is traceable to a version without
  // reading package.json — these files are served to every reader of the site.
  const body = readFileSync(dest, 'utf8');
  writeFileSync(dest, `/* ${name}@${version} — vendored copy, see tutor/package.json */\n${body}`);
  console.log(`  vendor/${to}  ${name}@${version}`);
}

const bytes = readFileSync(resolve(outDir, 'tutor-core.js')).length;
console.log(`  tutor-core.js  ${(bytes / 1024).toFixed(1)} kB  (${inputs.length} modules)`);
